// ─────────────────────────────────────────────────────────────────────────────
// Self-host the design-system fonts (Phase 4.1).
// Fetches woff2 from Google Fonts (latin + latin-ext for German diacritics),
// writes them to public/fonts/, and generates src/styles/fonts.css with
// font-display: swap. Run once (or when weights change):
//   node --experimental-strip-types scripts/fetch-fonts.ts
// ─────────────────────────────────────────────────────────────────────────────

import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FONTS_DIR = resolve(ROOT, 'public', 'fonts');
mkdirSync(FONTS_DIR, { recursive: true });

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';
const WANT_SUBSETS = new Set(['latin', 'latin-ext']);

type Face = { family: string; weight: string; api: string };
const FACES: Face[] = [
  { family: 'Archivo', weight: '700', api: 'Archivo:wght@700' },
  { family: 'Archivo', weight: '800', api: 'Archivo:wght@800' },
  { family: 'IBM Plex Sans', weight: '400', api: 'IBM+Plex+Sans:wght@400' },
  { family: 'IBM Plex Sans', weight: '600', api: 'IBM+Plex+Sans:wght@600' },
  { family: 'IBM Plex Sans', weight: '700', api: 'IBM+Plex+Sans:wght@700' },
  { family: 'IBM Plex Mono', weight: '500', api: 'IBM+Plex+Mono:wght@500' },
  { family: 'IBM Plex Mono', weight: '600', api: 'IBM+Plex+Mono:wght@600' },
];

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

const cssBlocks: string[] = [];

for (const face of FACES) {
  const url = `https://fonts.googleapis.com/css2?family=${face.api}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  const css = await res.text();
  // Split into (subset comment, @font-face block) pairs
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(css)) !== null) {
    const subset = m[1];
    if (!WANT_SUBSETS.has(subset)) continue;
    const block = m[2];
    const srcMatch = block.match(/src:\s*url\(([^)]+)\)\s*format\('woff2'\)/);
    const rangeMatch = block.match(/unicode-range:\s*([^;]+);/);
    if (!srcMatch) continue;
    const woffUrl = srcMatch[1];
    const fileName = `${slug(face.family)}-${face.weight}-${subset}.woff2`;
    const bin = new Uint8Array(await (await fetch(woffUrl, { headers: { 'User-Agent': UA } })).arrayBuffer());
    writeFileSync(resolve(FONTS_DIR, fileName), bin);
    cssBlocks.push(
      `@font-face {\n` +
      `  font-family: '${face.family}';\n` +
      `  font-style: normal;\n` +
      `  font-weight: ${face.weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${fileName}') format('woff2');\n` +
      (rangeMatch ? `  unicode-range: ${rangeMatch[1].trim()};\n` : '') +
      `}`
    );
    console.log(`  ✓ ${fileName} (${(bin.length / 1024).toFixed(1)} KB)`);
  }
}

const header = `/* Self-hosted fonts — generated by scripts/fetch-fonts.ts. Do not edit by hand. */\n`;
writeFileSync(resolve(ROOT, 'src', 'styles', 'fonts.css'), header + cssBlocks.join('\n\n') + '\n', 'utf8');
console.log(`\n[fetch-fonts] wrote ${cssBlocks.length} @font-face rules to src/styles/fonts.css`);
